name       : python-feedparser
version    : 5.2.1
release    : 3
source     :
    - https://pypi.python.org/packages/ca/f4/91a056f11751701c24f86c692d92fee290b0ba3f99f657cdeb85ad3da402/feedparser-5.2.1.tar.gz : bd030652c2d08532c034c27fcd7c85868e7fa3cb2b17f230a44a6bbc92519bf9
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : Universal feed parser
description: |
    Universal feed parser, handles RSS 0.9x, RSS 1.0, RSS 2.0, CDF, Atom 0.3, and Atom 1.0 feeds
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
